master:
  componentName: jenkins-master
  image: us.gcr.io/green-antonym-244311/jenkins-master
  overwriteConfig: true
  adminUser: admin
  installPlugins:
    - workflow-aggregator:2.6
    - workflow-job:2.33
    - credentials-binding:1.19
    - git:3.10.0
    - configuration-as-code:1.22
    - google-container-registry-auth:0.3
    - google-oauth-plugin:0.8
    - docker-workflow:1.18
    - google-kubernetes-engine:0.6.2