version: '3.3'
services:

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    hostname: mssql
    ports:
      - 1433:1433
    volumes:
      - dbdefault:/var/opt/mssql
      - ./configure_db.sql:/var/opt/configure_db.sql
    environment:
      - SA_PASSWORD=Pas5W0rD!
      - ACCEPT_EULA=Y
    container_name: db
    #command: /opt/mssql-tools/bin/sqlcmd -U sa -P Pas5W0rD! -i /var/opt/configure_db.sql -e


  server:
    image: autoshowroom:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      - spring.datasource.url=jdbc:sqlserver://db;databaseName=autoshowroom
      - spring.datasource.username=autoshowlogin
      - spring.datasource.password=autopassword
    container_name: autoshowroom

volumes:
  dbdefault:
    external: true