master:
  componentName: jenkins-master
  image: "jenkins/jenkins"
  overwriteConfig: true
  adminUser: admin
  installPlugins:
    - kubernetes:1.16.2
    - workflow-aggregator:2.6
    - workflow-job:2.33
    - credentials-binding:1.19
    - git:3.10.0
    - greenballs:1.15
    - google-login:1.4
    - role-strategy:2.11
    - locale:1.4
    - gradle:1.32
    - docker:1.1.6
    - configuration-as-code:1.22
    - google-container-registry-auth:0.3
    - docker-custom-build-environment:1.7.3
    - google-oauth-plugin:0.8
    - docker-workflow:1.18
    - docker-build-step:2.3
    - jobcacher:1.0
    - kubernetes-cli:1.6.0
  jobs:
    autoshowroom: |
      <?xml version='1.1' encoding='UTF-8'?>
      <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch@2.21">
        <actions/>
        <description></description>
        <properties>
          <org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty plugin="kubernetes@1.16.2">
            <permittedClouds/>
          </org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty>
          <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.3.9">
            <dockerLabel></dockerLabel>
            <registry plugin="docker-commons@1.15"/>
          </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
        </properties>
        <folderViews class="jenkins.branch.MultiBranchProjectViewHolder" plugin="branch-api@2.5.3">
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </folderViews>
        <healthMetrics/>
        <icon class="jenkins.branch.MetadataActionFolderIcon" plugin="branch-api@2.5.3">
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </icon>
        <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.9">
          <pruneDeadBranches>true</pruneDeadBranches>
          <daysToKeep>-1</daysToKeep>
          <numToKeep>-1</numToKeep>
        </orphanedItemStrategy>
        <triggers>
          <com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger plugin="cloudbees-folder@6.9">
            <spec>H/5 * * * *</spec>
            <interval>900000</interval>
          </com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger>
        </triggers>
        <disabled>false</disabled>
        <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@2.5.3">
          <data>
            <jenkins.branch.BranchSource>
              <source class="jenkins.plugins.git.GitSCMSource" plugin="git@3.10.0">
                <id>6f974fc2-4756-4e82-b054-9c82c534fd63</id>
                <remote>https://github.com/bepopov/autoshowroom.git</remote>
                <credentialsId></credentialsId>
                <traits>
                  <jenkins.plugins.git.traits.BranchDiscoveryTrait/>
                </traits>
              </source>
              <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
                <properties class="empty-list"/>
              </strategy>
            </jenkins.branch.BranchSource>
          </data>
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </sources>
        <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory">
          <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
          <scriptPath>server/Jenkinsfile</scriptPath>
        </factory>
      </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>
  JCasC:
    enabled: true
    configScripts:
      config: |
        security:
          apiToken:
            creationOfLegacyTokenEnabled: false
            tokenGenerationOnCreationEnabled: false
            usageStatisticsEnabled: true
          downloadSettings:
            useBrowser: false
          sSHD:
            port: -1
        unclassified:
          gitSCM:
            createAccountBasedOnEmail: false
          location:
            adminAddress: "address not configured yet <nobody@nowhere>"
            url: "http://jenkins:8080/"
          mailer:
            adminAddress: "address not configured yet <nobody@nowhere>"
            charset: "UTF-8"
            useSsl: false
          pollSCM:
            pollingThreadCount: 10
        tool:
          dockerTool:
            installations:
              - name: "Default"
                properties:
                  - installSource:
                      installers:
                        - docker:
                            version: "latest"
          git:
            installations:
              - home: "git"
                name: "Default"
          gradle:
            installations:
              - name: "Default"
                properties:
                  - installSource:
                      installers:
                        - gradleInstaller:
                            id: "5.5"

agent:
  image: us.gcr.io/green-antonym-244311/jenkins-slave
  alwaysPullImage: true
  volumes:
    - type: HostPath
      volumeName: docker-sock
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock