master:
  componentName: jenkins-master
  image: "jenkins/jenkins"
  overwriteConfig: true
  adminUser: admin
  installPlugins:
    - kubernetes:1.16.2
    - workflow-aggregator:2.6
    - workflow-job:2.33
    - credentials-binding:1.19
    - git:3.10.0
    - greenballs:1.15
    - google-login:1.4
    - role-strategy:2.11
    - locale:1.4
    - gradle:1.32
    - docker:1.1.6
    - configuration-as-code:1.22
    - google-container-registry-auth:0.3
    - docker-custom-build-environment:1.7.3
    - google-oauth-plugin:0.8
    - docker-workflow:1.18
    - docker-build-step:2.3
    - jobcacher:1.0
    - kubernetes-cli:1.6.0
  jobs:
    autoshowroom: |
      <?xml version='1.1' encoding='UTF-8'?>
      <flow-definition plugin="workflow-job@2.33">
        <actions>
          <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobAction plugin="pipeline-model-definition@1.3.9"/>
        </actions>
        <description>First trying to use Jenkinsfile</description>
        <keepDependencies>false</keepDependencies>
        <properties/>
        <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.70">
          <scm class="hudson.plugins.git.GitSCM" plugin="git@3.10.0">
            <configVersion>2</configVersion>
            <userRemoteConfigs>
              <hudson.plugins.git.UserRemoteConfig>
                <url>https://github.com/bepopov/autoshowroom.git</url>
              </hudson.plugins.git.UserRemoteConfig>
            </userRemoteConfigs>
            <branches>
              <hudson.plugins.git.BranchSpec>
                <name>*/jenkins</name>
              </hudson.plugins.git.BranchSpec>
            </branches>
            <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
            <submoduleCfg class="list"/>
            <extensions/>
          </scm>
          <scriptPath>server/Jenkinsfile</scriptPath>
          <lightweight>true</lightweight>
        </definition>
        <triggers/>
        <disabled>false</disabled>
      </flow-definition>
  JCasC:
    enabled: true
    configScripts:
      config: |
        security:
          apiToken:
            creationOfLegacyTokenEnabled: false
            tokenGenerationOnCreationEnabled: false
            usageStatisticsEnabled: true
          downloadSettings:
            useBrowser: false
          sSHD:
            port: -1
        unclassified:
          gitSCM:
            createAccountBasedOnEmail: false
          location:
            adminAddress: "address not configured yet <nobody@nowhere>"
            url: "http://jenkins:8080/"
          mailer:
            adminAddress: "address not configured yet <nobody@nowhere>"
            charset: "UTF-8"
            useSsl: false
          pollSCM:
            pollingThreadCount: 10
        tool:
          dockerTool:
            installations:
              - name: "Default"
                properties:
                  - installSource:
                      installers:
                        - docker:
                            version: "latest"
          git:
            installations:
              - home: "git"
                name: "Default"
          gradle:
            installations:
              - name: "Default"
                properties:
                  - installSource:
                      installers:
                        - gradleInstaller:
                            id: "5.5"

agent:
  image: us.gcr.io/green-antonym-244311/jenkins-slave
  alwaysPullImage: true
  volumes:
    - type: HostPath
      volumeName: docker-sock
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock